[package]
name = "orderbook"
version = "0.1.0"
authors = ["Mark Hudnall <me@markhudnall.com>"]
edition = "2018"

[dependencies]
rust_decimal = "1.8.1"
rbtree = "0.1"
uuid = { version = "0.5.1", features = ["serde", "v4"] }
